name: hii_messenger
description: Hii Messenger App with Glassy Theme
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.2.0
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true
