name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Setup Android & Firebase Engine
      run: |
        # 1. JSON File ko safe jagah (backup) mein copy karo
        mkdir -p /tmp/backup
        cp android/app/google-services.json /tmp/backup/ || echo "File abhi nahi hai"
        
        # 2. Android folder delete karke naya banao
        rm -rf android
        flutter create --platforms android .
        
        # 3. JSON File wapas rakho
        mkdir -p android/app
        cp /tmp/backup/google-services.json android/app/ || true
        
        # 4. PACKAGE NAME FIX (Sirf ID change hogi, andarni rasta nahi tootega)
        sed -i 's/applicationId = "com.example.hii_messenger"/applicationId = "com.example.hii"/g' android/app/build.gradle.kts
        
        # 5. Internet permission dalo
        sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET" />' android/app/src/main/AndroidManifest.xml
        
        # 6. Firebase Engine dalo
        sed -i '/id("com.android.application")/a \    id("com.google.gms.google-services") version "4.4.2" apply false' android/settings.gradle.kts
        sed -i '/id("com.android.application")/a \    id("com.google.gms.google-services")' android/app/build.gradle.kts

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK 
      run: flutter build apk --release --no-tree-shake-icons

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Hii-Messenger-App
        path: build/app/outputs/flutter-apk/app-release.apk
